# Generated by Django 5.0.2 on 2024-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='base_specifications',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
